   <h1>This is Plain HTML</h1>
    <p>So is this.</p>
    <p>This is HTML , but the day is generated by PHP: <?php
    echo date('l');
    ?>.</p>
    <h1>Example of embedding content:</h1>
    <h2>Editor's Choice</h2>
    <p>This week's recommended reading:</p>
    <h3><?php echo $title; ?></h3>
    <h4>by <?php print $author;  ?></h4>
    <h4><?php echo "$description  $answer"; ?></h4>
    <h4>Price: $<?php echo $price?></h4>